"""Build the per-domain GRPO pools (v10 layout): split the understanding training data into
focus/rest by domain, **one file per domain**.

FOCUS_DOMAINS / REST_DOMAINS below assign every domain to one of the two pools; the GRPO entry point
draws a focus batch with probability --focus_ratio and a rest batch otherwise.

Why one jsonl per domain: GRPO with `--pool_balance=1` samples uniformly **per file** (row weight
= 1 / number of rows of its file), so within a pool every domain is drawn at the same rate
regardless of its size. The three large domains are additionally reservoir-downsampled (caps in
CAP, seed 17) -- GRPO only draws samples, so a random subset of this size serves as the full set.
ST-Bench rows have their think cleared; the dataset automatically uses the no-reasoning rollout
prefix for rows with empty think (understanding_dataset._eff_reasoning), matching their evaluation
protocol, so no separate direct pool is needed. "Unlabeled" rows are dropped.

    python chronos_llm/scripts/utils/make_grpo_domain_pools_v10.py   # lightweight, streaming
"""
import json
import os
import random
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.insert(0, REPO)

from chronos_llm.scripts.utils.summarize_agg6_by_domain import domain_of  # noqa: E402

BASE = "data/understanding"
SOURCES = [
    f"{BASE}/veritime/veritime_train.jsonl",
    f"{BASE}/time-ra/time_ra_train.jsonl",
    f"{BASE}/opentslm/ecg_qa_train.jsonl",
    f"{BASE}/opentslm/har_train.jsonl",
    f"{BASE}/opentslm/sleep_train.jsonl",
    f"{BASE}/telecomts/telecomts_train.jsonl",
    f"{BASE}/hitsr/hitsr_train.jsonl",
    f"{BASE}/st-bench/stbench_train.jsonl",
]

FOCUS_DOMAINS = {
    "Urbanism", "Information_Technology", "Neuroscience", "Earth_Science",
    "Meteorology", "Manufacturing", "Energy",
}
REST_DOMAINS = {
    "Economics", "Bioacoustics",
    "Physiology", "Telecommunications", "Cross_domain_Synthetic",  # the three large domains
}
CAP = {"Physiology": 20000, "Telecommunications": 8000, "Cross_domain_Synthetic": 8000}

OUT_DIR = f"{BASE}/derived/grpo"
os.makedirs(OUT_DIR, exist_ok=True)
SLUG = lambda d: d.lower().replace("_", "")

rng = random.Random(17)
reservoir = {d: [] for d in CAP}
seen = {d: 0 for d in CAP}
writers, counts = {}, {}
n_drop = n_nothink = 0

def sink(dom):
    side = "focus" if dom in FOCUS_DOMAINS else "rest"
    if dom not in writers:
        writers[dom] = open(f"{OUT_DIR}/{side}_{SLUG(dom)}.jsonl", "w")
    return writers[dom]

for src in SOURCES:
    is_stb = "stbench" in os.path.basename(src)
    for line in open(src):
        row = json.loads(line)
        it = row.get("input_text")
        probe = dict(row, input_text="\n".join(map(str, it)) if isinstance(it, list) else it)
        d = domain_of(probe)
        if d == "Unlabeled":
            n_drop += 1
            continue
        assert d in FOCUS_DOMAINS or d in REST_DOMAINS, f"unassigned domain: {d}"
        if is_stb and row.get("think"):
            row["think"] = ""
            line = json.dumps(row, ensure_ascii=False) + "\n"
            n_nothink += 1
        if d in CAP:  # reservoir for the three large domains
            seen[d] += 1
            pool = reservoir[d]
            if len(pool) < CAP[d]:
                pool.append(line)
            else:
                j = rng.randint(0, seen[d] - 1)
                if j < CAP[d]:
                    pool[j] = line
            continue
        sink(d).write(line if line.endswith("\n") else line + "\n")
        counts[d] = counts.get(d, 0) + 1

for d, pool in reservoir.items():
    w = sink(d)
    for line in pool:
        w.write(line if line.endswith("\n") else line + "\n")
    counts[d] = len(pool)

for w in writers.values():
    w.close()

cfg = {"focus": [], "rest": []}
for d in sorted(counts):
    side = "focus" if d in FOCUS_DOMAINS else "rest"
    cfg[side].append(f"{OUT_DIR}/{side}_{SLUG(d)}.jsonl")
    print(f"{side:5s} {d:26s} {counts[d]:>7d} rows")
print(f"dropped {n_drop} Unlabeled rows; cleared think on {n_nothink} ST-Bench rows")

for side in ("focus", "rest"):
    p = f"{REPO}/chronos_llm/configs/grpo_{side}_pools.txt"   # the lists read by train_grpo_understanding.sh
    with open(p, "w") as f:
        f.write(f"# GRPO {side} pools (generated by make_grpo_domain_pools_v10.py, one file per domain for balancing)\n")
        f.write("\n".join(cfg[side]) + "\n")
    print(f"[written] {p} ({len(cfg[side])} files)")
