"""Physically split the test jsonl files of the MMTR understanding pool ("agg6") into part files of
~CHUNK rows each -- for batch runs of external baselines.

Motivation: the sharding mechanism of the baseline adapters (baseline_chattime_understanding /
baseline_chatts_2503 / baseline_timemqa / baseline_timeomni1_understanding /
baseline_timeomnivl_understanding) works at **file granularity** (file_shard_idx modulo the list).
agg6 has a few large files, so at file granularity the slowest shard is pinned by the largest file.
Rather than adding row-level sharding to every adapter, **cut the files physically**: part file names are all distinct => the
existing file-shard mechanism balances directly, and the file-level skip (skip when the output
exists) automatically becomes part-level resumption.

The split is **contiguous** (rows[i*K:(i+1)*K], not strided); concatenating parts in order restores
the original row order (`merge_agg6_baseline_parts.py`), and the scoring scripts
summarize_agg6_eval / by_domain read by original file name, unaware of the split.

    python chronos_llm/scripts/utils/split_agg6_for_baselines.py            # full split
    python chronos_llm/scripts/utils/split_agg6_for_baselines.py --check    # verify only, no writes

Outputs:
- parts:      <PARTS_DIR>/<stem>.partNN.jsonl
- list:       chronos_llm/configs/understanding_test_jsonl_agg6_parts.txt (all parts)
- smoke list: chronos_llm/configs/understanding_test_jsonl_agg6_smoke.txt (first part of every dataset)
"""
import argparse
import os

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
SRC_LIST = os.path.join(REPO, "chronos_llm/configs/understanding_test_jsonl_agg6.txt")
PARTS_DIR = "data/raw/agg6_baseline_parts"
PARTS_LIST = os.path.join(REPO, "chronos_llm/configs/understanding_test_jsonl_agg6_parts.txt")
SMOKE_LIST = os.path.join(REPO, "chronos_llm/configs/understanding_test_jsonl_agg6_smoke.txt")
CHUNK = 2500


def src_files():
    return [l.strip() for l in open(SRC_LIST) if l.strip() and not l.strip().startswith("#")]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="only verify row-count conservation of the existing parts, no writes")
    args = ap.parse_args()

    files = src_files()
    if args.check:
        ok = True
        for jf in files:
            stem = os.path.basename(jf)[: -len(".jsonl")]
            n_src = sum(1 for _ in open(jf))
            parts = sorted(f for f in os.listdir(PARTS_DIR) if f.startswith(stem + ".part"))
            n_parts = sum(sum(1 for _ in open(os.path.join(PARTS_DIR, p))) for p in parts)
            status = "OK" if n_src == n_parts else "MISMATCH"
            ok &= n_src == n_parts
            print(f"[{status}] {stem}: src={n_src} parts={n_parts} ({len(parts)} parts)")
        raise SystemExit(0 if ok else 1)

    os.makedirs(PARTS_DIR, exist_ok=True)
    all_parts, smoke_parts = [], []
    for jf in files:
        stem = os.path.basename(jf)[: -len(".jsonl")]
        n, pi, buf = 0, 0, []

        def flush():
            nonlocal pi, buf
            if not buf:
                return
            p = os.path.join(PARTS_DIR, f"{stem}.part{pi:02d}.jsonl")
            with open(p, "w") as f:
                f.writelines(buf)
            all_parts.append(p)
            if pi == 0:
                smoke_parts.append(p)
            pi += 1
            buf = []

        for line in open(jf):
            buf.append(line)
            n += 1
            if len(buf) >= CHUNK:
                flush()
        flush()
        print(f"{stem}: {n} rows -> {pi} parts")

    hdr = ("# Generated by split_agg6_for_baselines.py: physical split of the agg6 test jsonl files (%d rows/part),\n"
           "# for file-granularity sharded batch runs of external baselines; merge back to the original file names with merge_agg6_baseline_parts.py.\n")
    with open(PARTS_LIST, "w") as f:
        f.write(hdr % CHUNK)
        f.write("\n".join(all_parts) + "\n")
    with open(SMOKE_LIST, "w") as f:
        f.write("# Smoke list: the first part of every dataset (use together with --limit).\n")
        f.write("\n".join(smoke_parts) + "\n")
    print(f"{len(all_parts)} parts in total -> {PARTS_LIST}")


if __name__ == "__main__":
    main()
